/* Generated by scripts/gen-apple-stack-thunks.py - do not edit.
 * Darwin-ABI adapters for syscalls with more than 8 arguments (see the script for the reason). */

static BOOL WINAPI apple_stack_NtGdiAlphaBlend( ULONG_PTR a0, ULONG_PTR a1, ULONG_PTR a2, ULONG_PTR a3, ULONG_PTR a4, ULONG_PTR a5, ULONG_PTR a6, ULONG_PTR a7, ULONG_PTR a8, ULONG_PTR a9, ULONG_PTR a10, ULONG_PTR a11 )
{
    return NtGdiAlphaBlend( (HDC)a0, (int)a1, (int)a2, (int)a3, (int)a4, (HDC)a5, (int)a6, (int)a7, (int)a8, (int)a9, (DWORD)a10, (HANDLE)a11 );
}

static BOOL WINAPI apple_stack_NtGdiArcInternal( ULONG_PTR a0, ULONG_PTR a1, ULONG_PTR a2, ULONG_PTR a3, ULONG_PTR a4, ULONG_PTR a5, ULONG_PTR a6, ULONG_PTR a7, ULONG_PTR a8, ULONG_PTR a9 )
{
    return NtGdiArcInternal( (UINT)a0, (HDC)a1, (INT)a2, (INT)a3, (INT)a4, (INT)a5, (INT)a6, (INT)a7, (INT)a8, (INT)a9 );
}

static BOOL WINAPI apple_stack_NtGdiBitBlt( ULONG_PTR a0, ULONG_PTR a1, ULONG_PTR a2, ULONG_PTR a3, ULONG_PTR a4, ULONG_PTR a5, ULONG_PTR a6, ULONG_PTR a7, ULONG_PTR a8, ULONG_PTR a9, ULONG_PTR a10 )
{
    return NtGdiBitBlt( (HDC)a0, (INT)a1, (INT)a2, (INT)a3, (INT)a4, (HDC)a5, (INT)a6, (INT)a7, (DWORD)a8, (DWORD)a9, (FLONG)a10 );
}

static HBITMAP WINAPI apple_stack_NtGdiCreateDIBSection( ULONG_PTR a0, ULONG_PTR a1, ULONG_PTR a2, ULONG_PTR a3, ULONG_PTR a4, ULONG_PTR a5, ULONG_PTR a6, ULONG_PTR a7, ULONG_PTR a8 )
{
    return NtGdiCreateDIBSection( (HDC)a0, (HANDLE)a1, (DWORD)a2, (const BITMAPINFO *)a3, (UINT)a4, (UINT)a5, (ULONG)a6, (ULONG_PTR)a7, (void **)a8 );
}

static HBITMAP WINAPI apple_stack_NtGdiCreateDIBitmapInternal( ULONG_PTR a0, ULONG_PTR a1, ULONG_PTR a2, ULONG_PTR a3, ULONG_PTR a4, ULONG_PTR a5, ULONG_PTR a6, ULONG_PTR a7, ULONG_PTR a8, ULONG_PTR a9, ULONG_PTR a10 )
{
    return NtGdiCreateDIBitmapInternal( (HDC)a0, (INT)a1, (INT)a2, (DWORD)a3, (const void *)a4, (const BITMAPINFO *)a5, (UINT)a6, (UINT)a7, (UINT)a8, (ULONG)a9, (HANDLE)a10 );
}

static HPEN WINAPI apple_stack_NtGdiExtCreatePen( ULONG_PTR a0, ULONG_PTR a1, ULONG_PTR a2, ULONG_PTR a3, ULONG_PTR a4, ULONG_PTR a5, ULONG_PTR a6, ULONG_PTR a7, ULONG_PTR a8, ULONG_PTR a9, ULONG_PTR a10 )
{
    return NtGdiExtCreatePen( (DWORD)a0, (DWORD)a1, (ULONG)a2, (ULONG)a3, (ULONG_PTR)a4, (ULONG_PTR)a5, (DWORD)a6, (const DWORD *)a7, (ULONG)a8, (BOOL)a9, (HBRUSH)a10 );
}

static BOOL WINAPI apple_stack_NtGdiExtTextOutW( ULONG_PTR a0, ULONG_PTR a1, ULONG_PTR a2, ULONG_PTR a3, ULONG_PTR a4, ULONG_PTR a5, ULONG_PTR a6, ULONG_PTR a7, ULONG_PTR a8 )
{
    return NtGdiExtTextOutW( (HDC)a0, (INT)a1, (INT)a2, (UINT)a3, (const RECT *)a4, (const WCHAR *)a5, (UINT)a6, (const INT *)a7, (DWORD)a8 );
}

static INT WINAPI apple_stack_NtGdiGetDIBitsInternal( ULONG_PTR a0, ULONG_PTR a1, ULONG_PTR a2, ULONG_PTR a3, ULONG_PTR a4, ULONG_PTR a5, ULONG_PTR a6, ULONG_PTR a7, ULONG_PTR a8 )
{
    return NtGdiGetDIBitsInternal( (HDC)a0, (HBITMAP)a1, (UINT)a2, (UINT)a3, (void *)a4, (BITMAPINFO *)a5, (UINT)a6, (UINT)a7, (UINT)a8 );
}

static BOOL WINAPI apple_stack_NtGdiMaskBlt( ULONG_PTR a0, ULONG_PTR a1, ULONG_PTR a2, ULONG_PTR a3, ULONG_PTR a4, ULONG_PTR a5, ULONG_PTR a6, ULONG_PTR a7, ULONG_PTR a8, ULONG_PTR a9, ULONG_PTR a10, ULONG_PTR a11, ULONG_PTR a12 )
{
    return NtGdiMaskBlt( (HDC)a0, (INT)a1, (INT)a2, (INT)a3, (INT)a4, (HDC)a5, (INT)a6, (INT)a7, (HBITMAP)a8, (INT)a9, (INT)a10, (DWORD)a11, (DWORD)a12 );
}

static BOOL WINAPI apple_stack_NtGdiPlgBlt( ULONG_PTR a0, ULONG_PTR a1, ULONG_PTR a2, ULONG_PTR a3, ULONG_PTR a4, ULONG_PTR a5, ULONG_PTR a6, ULONG_PTR a7, ULONG_PTR a8, ULONG_PTR a9, ULONG_PTR a10 )
{
    return NtGdiPlgBlt( (HDC)a0, (const POINT *)a1, (HDC)a2, (INT)a3, (INT)a4, (INT)a5, (INT)a6, (HBITMAP)a7, (INT)a8, (INT)a9, (DWORD)a10 );
}

static INT WINAPI apple_stack_NtGdiSetDIBitsToDeviceInternal( ULONG_PTR a0, ULONG_PTR a1, ULONG_PTR a2, ULONG_PTR a3, ULONG_PTR a4, ULONG_PTR a5, ULONG_PTR a6, ULONG_PTR a7, ULONG_PTR a8, ULONG_PTR a9, ULONG_PTR a10, ULONG_PTR a11, ULONG_PTR a12, ULONG_PTR a13, ULONG_PTR a14, ULONG_PTR a15 )
{
    return NtGdiSetDIBitsToDeviceInternal( (HDC)a0, (INT)a1, (INT)a2, (DWORD)a3, (DWORD)a4, (INT)a5, (INT)a6, (UINT)a7, (UINT)a8, (const void *)a9, (const BITMAPINFO *)a10, (UINT)a11, (UINT)a12, (UINT)a13, (BOOL)a14, (HANDLE)a15 );
}

static BOOL WINAPI apple_stack_NtGdiStretchBlt( ULONG_PTR a0, ULONG_PTR a1, ULONG_PTR a2, ULONG_PTR a3, ULONG_PTR a4, ULONG_PTR a5, ULONG_PTR a6, ULONG_PTR a7, ULONG_PTR a8, ULONG_PTR a9, ULONG_PTR a10, ULONG_PTR a11 )
{
    return NtGdiStretchBlt( (HDC)a0, (INT)a1, (INT)a2, (INT)a3, (INT)a4, (HDC)a5, (INT)a6, (INT)a7, (INT)a8, (INT)a9, (DWORD)a10, (COLORREF)a11 );
}

static INT WINAPI apple_stack_NtGdiStretchDIBitsInternal( ULONG_PTR a0, ULONG_PTR a1, ULONG_PTR a2, ULONG_PTR a3, ULONG_PTR a4, ULONG_PTR a5, ULONG_PTR a6, ULONG_PTR a7, ULONG_PTR a8, ULONG_PTR a9, ULONG_PTR a10, ULONG_PTR a11, ULONG_PTR a12, ULONG_PTR a13, ULONG_PTR a14, ULONG_PTR a15 )
{
    return NtGdiStretchDIBitsInternal( (HDC)a0, (INT)a1, (INT)a2, (INT)a3, (INT)a4, (INT)a5, (INT)a6, (INT)a7, (INT)a8, (const void *)a9, (const BITMAPINFO *)a10, (UINT)a11, (DWORD)a12, (UINT)a13, (UINT)a14, (HANDLE)a15 );
}

static BOOL WINAPI apple_stack_NtGdiTransparentBlt( ULONG_PTR a0, ULONG_PTR a1, ULONG_PTR a2, ULONG_PTR a3, ULONG_PTR a4, ULONG_PTR a5, ULONG_PTR a6, ULONG_PTR a7, ULONG_PTR a8, ULONG_PTR a9, ULONG_PTR a10 )
{
    return NtGdiTransparentBlt( (HDC)a0, (int)a1, (int)a2, (int)a3, (int)a4, (HDC)a5, (int)a6, (int)a7, (int)a8, (int)a9, (UINT)a10 );
}

static HWND WINAPI apple_stack_NtUserCreateWindowEx( ULONG_PTR a0, ULONG_PTR a1, ULONG_PTR a2, ULONG_PTR a3, ULONG_PTR a4, ULONG_PTR a5, ULONG_PTR a6, ULONG_PTR a7, ULONG_PTR a8, ULONG_PTR a9, ULONG_PTR a10, ULONG_PTR a11, ULONG_PTR a12, ULONG_PTR a13, ULONG_PTR a14, ULONG_PTR a15, ULONG_PTR a16 )
{
    return NtUserCreateWindowEx( (DWORD)a0, (UNICODE_STRING *)a1, (UNICODE_STRING *)a2, (UNICODE_STRING *)a3, (DWORD)a4, (INT)a5, (INT)a6, (INT)a7, (INT)a8, (HWND)a9, (HMENU)a10, (HINSTANCE)a11, (void *)a12, (DWORD)a13, (HINSTANCE)a14, (const WCHAR *)a15, (BOOL)a16 );
}

static HDWP WINAPI apple_stack_NtUserDeferWindowPosAndBand( ULONG_PTR a0, ULONG_PTR a1, ULONG_PTR a2, ULONG_PTR a3, ULONG_PTR a4, ULONG_PTR a5, ULONG_PTR a6, ULONG_PTR a7, ULONG_PTR a8, ULONG_PTR a9 )
{
    return NtUserDeferWindowPosAndBand( (HDWP)a0, (HWND)a1, (HWND)a2, (INT)a3, (INT)a4, (INT)a5, (INT)a6, (UINT)a7, (UINT)a8, (UINT)a9 );
}

static BOOL WINAPI apple_stack_NtUserDrawIconEx( ULONG_PTR a0, ULONG_PTR a1, ULONG_PTR a2, ULONG_PTR a3, ULONG_PTR a4, ULONG_PTR a5, ULONG_PTR a6, ULONG_PTR a7, ULONG_PTR a8 )
{
    return NtUserDrawIconEx( (HDC)a0, (INT)a1, (INT)a2, (HICON)a3, (INT)a4, (INT)a5, (UINT)a6, (HBRUSH)a7, (UINT)a8 );
}

static BOOL WINAPI apple_stack_NtUserUpdateLayeredWindow( ULONG_PTR a0, ULONG_PTR a1, ULONG_PTR a2, ULONG_PTR a3, ULONG_PTR a4, ULONG_PTR a5, ULONG_PTR a6, ULONG_PTR a7, ULONG_PTR a8, ULONG_PTR a9 )
{
    return NtUserUpdateLayeredWindow( (HWND)a0, (HDC)a1, (const POINT *)a2, (const SIZE *)a3, (HDC)a4, (const POINT *)a5, (COLORREF)a6, (const BLENDFUNCTION *)a7, (DWORD)a8, (const RECT *)a9 );
}
