/* Generated by scripts/gen-apple-stack-thunks.py - do not edit.
 * Darwin-ABI adapters for syscalls with more than 8 arguments (see the script for the reason). */
#undef NtGdiAlphaBlend
#undef NtGdiArcInternal
#undef NtGdiBitBlt
#undef NtGdiCreateDIBSection
#undef NtGdiCreateDIBitmapInternal
#undef NtGdiExtCreatePen
#undef NtGdiExtTextOutW
#undef NtGdiGetDIBitsInternal
#undef NtGdiMaskBlt
#undef NtGdiPlgBlt
#undef NtGdiSetDIBitsToDeviceInternal
#undef NtGdiStretchBlt
#undef NtGdiStretchDIBitsInternal
#undef NtGdiTransparentBlt
#undef NtUserCreateWindowEx
#undef NtUserDeferWindowPosAndBand
#undef NtUserDrawIconEx
#undef NtUserUpdateLayeredWindow
