/* Generated by scripts/gen-apple-stack-thunks.py - do not edit.
 * Darwin-ABI adapters for syscalls with more than 8 arguments (see the script for the reason). */
#undef NtAccessCheckAndAuditAlarm
#undef NtAccessCheckByTypeAndAuditAlarm
#undef NtCreateFile
#undef NtCreateLowBoxToken
#undef NtCreateNamedPipeFile
#undef NtCreateSectionEx
#undef NtCreateThreadEx
#undef NtCreateToken
#undef NtCreateTransaction
#undef NtCreateUserProcess
#undef NtDeviceIoControlFile
#undef NtFsControlFile
#undef NtLockFile
#undef NtMapViewOfSection
#undef NtMapViewOfSectionEx
#undef NtNotifyChangeDirectoryFile
#undef NtNotifyChangeKey
#undef NtNotifyChangeMultipleKeys
#undef NtQueryDirectoryFile
#undef NtQueryEaFile
#undef NtReadFile
#undef NtReadFileScatter
#undef NtSecureConnectPort
#undef NtWriteFile
#undef NtWriteFileGather
